<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
    <PropertyGroup>
        <TargetFramework>net10.0-browser</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <WasmEnableThreads>false</WasmEnableThreads>
        <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    </PropertyGroup>

    <PropertyGroup Condition="'$(Configuration)' == 'Release'">
        <RunAOTCompilation>true</RunAOTCompilation>
        <PublishTrimmed>true</PublishTrimmed>
        <TrimMode>full</TrimMode>
        <CompressionEnabled>true</CompressionEnabled>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Avalonia.Browser" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\Material3.Gallery.UI\Material3.Gallery.UI.csproj" />
    </ItemGroup>
</Project>
